
/*
 * WhatsApp protocol dissector
 * Written by David Guillen Fandos <david@davidgf.net>
 * Based on WhatsAPI sources
 *
 */


#include <config.h>
#include <epan/packet.h>
#include <epan/prefs.h>

#define WHATSAPP_PORT 5222
#define WHATSAPP_PORT_NEW 443

const char * global_imei_whatsapp_1 = 0;
const char * global_v2pw_whatsapp_1 = 0;
const char * global_v2pw_whatsapp_2 = 0;
const char * global_v2pw_whatsapp_3 = 0;
const char * global_v2pw_whatsapp_4 = 0;
const char * global_v2pw_whatsapp_5 = 0;
const char * global_v2pw_whatsapp_6 = 0;
const gboolean global_enable_decoding;
int proto_whatsapp = -1;
int message_whatsapp = -1;
int userserver_string = -1;
int tree_whatsapp = -1;
static gint ett_whatsapp = -1;
int whatsapp_msg_crypted_payload = -1;
int whatsapp_msg_crypted_message = -1;

/* Variables for whatsapp packets */
int hf_whatsapp_message = -1;
int hf_whatsapp_node = -1;
int hf_whatsapp_nodesize16 = -1;
int hf_whatsapp_nodesize8 = -1;
int hf_whatsapp_attr_key_enc_12 = -1;
int hf_whatsapp_attr_val_enc_12 = -1;
int hf_whatsapp_attr_key_enc_14 = -1;
int hf_whatsapp_attr_val_enc_14 = -1;
int hf_whatsapp_attr_key_enc_ext = -1;
int hf_whatsapp_attr_val_enc_ext = -1;
int hf_whatsapp_attr_key_plain = -1;
int hf_whatsapp_attr_val_plain = -1;
int hf_whatsapp_attr_crypted = -1;
int hf_whatsapp_attr_flags = -1;
int hf_whatsapp_attribute = -1;
int hf_whatsapp_tag_enc_12 = -1;
int hf_whatsapp_tag_enc_14 = -1;
int hf_whatsapp_tag_enc_ext = -1;
int hf_whatsapp_tag_plain = -1;
int hf_whatsapp_nvalue_enc_12 = -1;
int hf_whatsapp_nvalue_enc_14 = -1;
int hf_whatsapp_nvalue_enc_ext = -1;
int hf_whatsapp_nvalue_plain = -1;
int hf_whatsapp_crypted_hmac_hash = -1;
int hf_whatsapp_userserver = -1;

const value_string strings_list12[];
const value_string strings_list14[];
const value_string strings_list_ext[];

int whatsapp_msg = -1;

#define MIN_PAKCET_SIZE 4


static guint get_whatsapp_message_len(packet_info *pinfo, tvbuff_t *tvb, int offset)
{
  int length = tvb_length(tvb)-offset;
  guint8* buffer = tvb_memdup(NULL, tvb, offset, length);
  int wa_len = whatsapp_data_length(buffer, length);
  g_free(buffer);
  return wa_len;
}

static void dissect_whatsapp_message(tvbuff_t *tvb, packet_info *pinfo, proto_tree *tree)
{
  col_set_str (pinfo-> cinfo, COL_PROTOCOL, "WhatsApp XMPP protocol packet");
  col_clear (pinfo->cinfo, COL_INFO);

  if (tree) {
    proto_item *ti = proto_tree_add_item (tree, proto_whatsapp, tvb, 0,-1, ENC_NA);
    proto_tree * subtree = proto_item_add_subtree (ti, message_whatsapp);

    int length = tvb_length(tvb);
    guint8* buffer = tvb_memdup(NULL, tvb, 0, length);
    whatsapp_data_dissect_tree(buffer, length, subtree, tvb, pinfo);
    g_free(buffer);
  }
  return; // tvb_length(tvb);
}

static int dissect_whatsapp (tvbuff_t *tvb, packet_info *pinfo, proto_tree *tree) {
  tcp_dissect_pdus(tvb, pinfo, tree, TRUE, MIN_PAKCET_SIZE,
                     get_whatsapp_message_len, dissect_whatsapp_message);
}
void proto_reg_handoff_whatsapp(void);

void proto_register_whatsapp(void) {
  static hf_register_info hf_whatsapp[] = {
    { &whatsapp_msg,
        { "Message", "whatsapp.message",
          FT_NONE, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &whatsapp_msg_crypted_payload,
        { "Crypted payload", "whatsapp.payload",
          FT_NONE, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &whatsapp_msg_crypted_message,
        { "Crypted message", "whatsapp.crypted_message",
          FT_NONE, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_message,
        { "Message size", "whatsapp.message",
          FT_UINT16, BASE_DEC,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_node,
        { "Node", "whatsapp.node",
          FT_NONE, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_nodesize16,
        { "Size", "whatsapp.node",
          FT_UINT16, BASE_DEC,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attribute,
        { "Attribute", "whatsapp.attr",
          FT_NONE, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_userserver,
        { "User@Server", "whatsapp.userserver",
          FT_NONE, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_nodesize8,
        { "Size", "whatsapp.node",
          FT_UINT8, BASE_DEC,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_key_enc_12,
        { "Key", "whatsapp.keyenc12",
          FT_UINT8, BASE_DEC,
          VALS(strings_list12), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_val_enc_12,
        { "Value", "whatsapp.valueenc12",
          FT_UINT8, BASE_DEC,
          VALS(strings_list12), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_key_enc_14,
        { "Key", "whatsapp.keyenc14",
          FT_UINT8, BASE_DEC,
          VALS(strings_list14), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_val_enc_14,
        { "Value", "whatsapp.valueenc14",
          FT_UINT8, BASE_DEC,
          VALS(strings_list14), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_key_enc_ext,
        { "Key", "whatsapp.keyencext",
          FT_UINT8, BASE_DEC,
          VALS(strings_list_ext), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_val_enc_ext,
        { "Value", "whatsapp.valueencext",
          FT_UINT8, BASE_DEC,
          VALS(strings_list_ext), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_key_plain,
        { "Key", "whatsapp.keyplain",
          FT_STRING, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_val_plain,
        { "Value", "whatsapp.valueplain",
          FT_STRING, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_tag_enc_12,
        { "Tag", "whatsapp.tagenc12",
          FT_UINT8, BASE_DEC,
          VALS(strings_list12), 0x0,
          NULL, HFILL },
    },    
    { &hf_whatsapp_tag_enc_14,
        { "Tag", "whatsapp.tagenc14",
          FT_UINT8, BASE_DEC,
          VALS(strings_list14), 0x0,
          NULL, HFILL },
    },    
    { &hf_whatsapp_tag_enc_ext,
        { "Tag", "whatsapp.tagencext",
          FT_UINT8, BASE_DEC,
          VALS(strings_list_ext), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_tag_plain,
        { "Tag", "whatsapp.tagplain",
          FT_STRING, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_nvalue_enc_12,
        { "Value", "whatsapp.nodevalueenc12",
          FT_UINT8, BASE_DEC,
          VALS(strings_list12), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_nvalue_enc_14,
        { "Value", "whatsapp.nodevalueenc14",
          FT_UINT8, BASE_DEC,
          VALS(strings_list14), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_nvalue_enc_ext,
        { "Value", "whatsapp.nodevalueencext",
          FT_UINT8, BASE_DEC,
          VALS(strings_list_ext), 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_nvalue_plain,
        { "Value", "whatsapp.nodevalueplain",
          FT_STRING, BASE_NONE,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_flags,
        { "Flags", "whatsapp.flags",
          FT_UINT8, BASE_HEX,
          NULL, 0x0,
          NULL, HFILL },
    },
    { &hf_whatsapp_attr_crypted,
        { "Crypted", "whatsapp.crypted",
          FT_BOOLEAN, BASE_NONE,
          NULL, 0x80,
          NULL, HFILL },
    },
    { &hf_whatsapp_crypted_hmac_hash,
        { "HMAC-SHA1", "whatsapp.crypt_hash",
          FT_UINT32, BASE_HEX,
          NULL, 0x0,
          NULL, HFILL },
    }
  };
  static gint *ett_whatsapp_arr[] = { /* protocol subtree array */
    &message_whatsapp,
    &tree_whatsapp,
    &userserver_string
  };
  proto_whatsapp = proto_register_protocol(
    "WhatsApp XMPP protocol", "WhatsApp", "whatsapp");
  proto_register_field_array (proto_whatsapp, hf_whatsapp, array_length (hf_whatsapp));
  proto_register_subtree_array (ett_whatsapp_arr, array_length (ett_whatsapp_arr));
  
  struct pref_module * whatsapp_module = 
		(struct pref_module *)prefs_register_protocol(proto_whatsapp, proto_reg_handoff_whatsapp);
  prefs_register_string_preference(whatsapp_module, "imei1",
				 "Phone IMEI (1)",
				 "Telephone IMEI to use as key",
				 &global_imei_whatsapp_1);
  prefs_register_string_preference(whatsapp_module, "pw1",
				 "v2 password (1)",
				 "Base64 encoded password to use in v2 auth",
				 &global_v2pw_whatsapp_1);
  prefs_register_string_preference(whatsapp_module, "pw2",
				 "v2 password (2)",
				 "Base64 encoded password to use in v2 auth",
				 &global_v2pw_whatsapp_2);
  prefs_register_string_preference(whatsapp_module, "pw3",
				 "v2 password (3)",
				 "Base64 encoded password to use in v2 auth",
				 &global_v2pw_whatsapp_3);
  prefs_register_string_preference(whatsapp_module, "pw4",
				 "v2 password (4)",
				 "Base64 encoded password to use in v2 auth",
				 &global_v2pw_whatsapp_4);
  prefs_register_string_preference(whatsapp_module, "pw5",
				 "v2 password (5)",
				 "Base64 encoded password to use in v2 auth",
				 &global_v2pw_whatsapp_5);
  prefs_register_string_preference(whatsapp_module, "pw6",
				 "v2 password (6)",
				 "Base64 encoded password to use in v2 auth",
				 &global_v2pw_whatsapp_6);
  prefs_register_bool_preference(whatsapp_module, "enable_decoding",
				 "Enable packet decoding",
				 "Decodes network traffic if possible",
				 &global_enable_decoding);
}

void proto_reg_handoff_whatsapp(void) {
  static dissector_handle_t whatsapp_handle;
  whatsapp_handle = new_create_dissector_handle (dissect_whatsapp, proto_whatsapp);
  dissector_add_uint ("tcp.port", WHATSAPP_PORT, whatsapp_handle);
  dissector_add_uint ("tcp.port", WHATSAPP_PORT_NEW, whatsapp_handle);
}



const value_string strings_list12[] = {
	{ 0,"" },
	{ 1,"" },
	{ 2,"" },
	{ 3,"" },
	{ 4,"" },
	{ 5,"account" },
	{ 6,"ack" },
	{ 7,"action" },
	{ 8,"active" },
	{ 9,"add" },
	{ 10,"after" },
	{ 11,"ib" },
	{ 12,"all" },
	{ 13,"allow" },
	{ 14,"apple" },
	{ 15,"audio" },
	{ 16,"auth" },
	{ 17,"author" },
	{ 18,"available" },
	{ 19,"bad-protocol" },
	{ 20,"bad-request" },
	{ 21,"before" },
	{ 22,"Bell.caf" },
	{ 23,"body" },
	{ 24,"Boing.caf" },
	{ 25,"cancel" },
	{ 26,"category" },
	{ 27,"challenge" },
	{ 28,"chat" },
	{ 29,"clean" },
	{ 30,"code" },
	{ 31,"composing" },
	{ 32,"config" },
	{ 33,"conflict" },
	{ 34,"contacts" },
	{ 35,"count" },
	{ 36,"create" },
	{ 37,"creation" },
	{ 38,"default" },
	{ 39,"delay" },
	{ 40,"delete" },
	{ 41,"delivered" },
	{ 42,"deny" },
	{ 43,"digest" },
	{ 44,"DIGEST-MD5-1" },
	{ 45,"DIGEST-MD5-2" },
	{ 46,"dirty" },
	{ 47,"elapsed" },
	{ 48,"broadcast" },
	{ 49,"enable" },
	{ 50,"encoding" },
	{ 51,"duplicate" },
	{ 52,"error" },
	{ 53,"event" },
	{ 54,"expiration" },
	{ 55,"expired" },
	{ 56,"fail" },
	{ 57,"failure" },
	{ 58,"false" },
	{ 59,"favorites" },
	{ 60,"feature" },
	{ 61,"features" },
	{ 62,"field" },
	{ 63,"first" },
	{ 64,"free" },
	{ 65,"from" },
	{ 66,"g.us" },
	{ 67,"get" },
	{ 68,"Glass.caf" },
	{ 69,"google" },
	{ 70,"group" },
	{ 71,"groups" },
	{ 72,"g_notify" },
	{ 73,"g_sound" },
	{ 74,"Harp.caf" },
	{ 75,"http://etherx.jabber.org/streams" },
	{ 76,"http://jabber.org/protocol/chatstates" },
	{ 77,"id" },
	{ 78,"image" },
	{ 79,"img" },
	{ 80,"inactive" },
	{ 81,"index" },
	{ 82,"internal-server-error" },
	{ 83,"invalid-mechanism" },
	{ 84,"ip" },
	{ 85,"iq" },
	{ 86,"item" },
	{ 87,"item-not-found" },
	{ 88,"user-not-found" },
	{ 89,"jabber:iq:last" },
	{ 90,"jabber:iq:privacy" },
	{ 91,"jabber:x:delay" },
	{ 92,"jabber:x:event" },
	{ 93,"jid" },
	{ 94,"jid-malformed" },
	{ 95,"kind" },
	{ 96,"last" },
	{ 97,"latitude" },
	{ 98,"lc" },
	{ 99,"leave" },
	{ 100,"leave-all" },
	{ 101,"lg" },
	{ 102,"list" },
	{ 103,"location" },
	{ 104,"longitude" },
	{ 105,"max" },
	{ 106,"max_groups" },
	{ 107,"max_participants" },
	{ 108,"max_subject" },
	{ 109,"mechanism" },
	{ 110,"media" },
	{ 111,"message" },
	{ 112,"message_acks" },
	{ 113,"method" },
	{ 114,"microsoft" },
	{ 115,"missing" },
	{ 116,"modify" },
	{ 117,"mute" },
	{ 118,"name" },
	{ 119,"nokia" },
	{ 120,"none" },
	{ 121,"not-acceptable" },
	{ 122,"not-allowed" },
	{ 123,"not-authorized" },
	{ 124,"notification" },
	{ 125,"notify" },
	{ 126,"off" },
	{ 127,"offline" },
	{ 128,"order" },
	{ 129,"owner" },
	{ 130,"owning" },
	{ 131,"paid" },
	{ 132,"participant" },
	{ 133,"participants" },
	{ 134,"participating" },
	{ 135,"password" },
	{ 136,"paused" },
	{ 137,"picture" },
	{ 138,"pin" },
	{ 139,"ping" },
	{ 140,"platform" },
	{ 141,"pop_mean_time" },
	{ 142,"pop_plus_minus" },
	{ 143,"port" },
	{ 144,"presence" },
	{ 145,"preview" },
	{ 146,"probe" },
	{ 147,"proceed" },
	{ 148,"prop" },
	{ 149,"props" },
	{ 150,"p_o" },
	{ 151,"p_t" },
	{ 152,"query" },
	{ 153,"raw" },
	{ 154,"reason" },
	{ 155,"receipt" },
	{ 156,"receipt_acks" },
	{ 157,"received" },
	{ 158,"registration" },
	{ 159,"relay" },
	{ 160,"remote-server-timeout" },
	{ 161,"remove" },
	{ 162,"Replaced by new connection" },
	{ 163,"request" },
	{ 164,"required" },
	{ 165,"resource" },
	{ 166,"resource-constraint" },
	{ 167,"response" },
	{ 168,"result" },
	{ 169,"retry" },
	{ 170,"rim" },
	{ 171,"s.whatsapp.net" },
	{ 172,"s.us" },
	{ 173,"seconds" },
	{ 174,"server" },
	{ 175,"server-error" },
	{ 176,"service-unavailable" },
	{ 177,"set" },
	{ 178,"show" },
	{ 179,"sid" },
	{ 180,"silent" },
	{ 181,"sound" },
	{ 182,"stamp" },
	{ 183,"unsubscribe" },
	{ 184,"stat" },
	{ 185,"status" },
	{ 186,"stream:error" },
	{ 187,"stream:features" },
	{ 188,"subject" },
	{ 189,"subscribe" },
	{ 190,"success" },
	{ 191,"sync" },
	{ 192,"system-shutdown" },
	{ 193,"s_o" },
	{ 194,"s_t" },
	{ 195,"t" },
	{ 196,"text" },
	{ 197,"timeout" },
	{ 198,"TimePassing.caf" },
	{ 199,"timestamp" },
	{ 200,"to" },
	{ 201,"Tri-tone.caf" },
	{ 202,"true" },
	{ 203,"type" },
	{ 204,"unavailable" },
	{ 205,"uri" },
	{ 206,"url" },
	{ 207,"urn:ietf:params:xml:ns:xmpp-sasl" },
	{ 208,"urn:ietf:params:xml:ns:xmpp-stanzas" },
	{ 209,"urn:ietf:params:xml:ns:xmpp-streams" },
	{ 210,"urn:xmpp:delay" },
	{ 211,"urn:xmpp:ping" },
	{ 212,"urn:xmpp:receipts" },
	{ 213,"urn:xmpp:whatsapp" },
	{ 214,"urn:xmpp:whatsapp:account" },
	{ 215,"urn:xmpp:whatsapp:dirty" },
	{ 216,"urn:xmpp:whatsapp:mms" },
	{ 217,"urn:xmpp:whatsapp:push" },
	{ 218,"user" },
	{ 219,"username" },
	{ 220,"value" },
	{ 221,"vcard" },
	{ 222,"version" },
	{ 223,"video" },
	{ 224,"w" },
	{ 225,"w:g" },
	{ 226,"w:p" },
	{ 227,"w:p:r" },
	{ 228,"w:profile:picture" },
	{ 229,"wait" },
	{ 230,"x" },
	{ 231,"xml-not-well-formed" },
	{ 232,"xmlns" },
	{ 233,"xmlns:stream" },
	{ 234,"Xylophone.caf" },
	{ 235,"1" },
	{ 236,"WAUTH-1" },
	{ 237,"" },
	{ 238,"" },
	{ 239,"" },
	{ 240,"" },
	{ 241,"" },
	{ 242,"" },
	{ 243,"" },
	{ 244,"" },
	{ 245,"" },
	{ 246,"" },
	{ 247,"" },
	{ 248,"XXX" },
	{ 249,"" },
	{ 250,"" },
	{ 251,"" },
	{ 252,"" },
	{ 253,"" },
	{ 254,"" },
	{ 255,"" },
	{0,NULL}
};

const value_string strings_list14[] = {
	{0, ""},
	{1, ""},
	{2, ""},
	{3, "account"},
	{4, "ack"},
	{5, "action"},
	{6, "active"},
	{7, "add"},
	{8, "after"},
	{9, "all"},
	{10, "allow"},
	{11, "apple"},
	{12, "auth"},
	{13, "author"},
	{14, "available"},
	{15, "bad-protocol"},
	{16, "bad-request"},
	{17, "before"},
	{18, "body"},
	{19, "broadcast"},
	{20, "cancel"},
	{21, "category"},
	{22, "challenge"},
	{23, "chat"},
	{24, "clean"},
	{25, "code"},
	{26, "composing"},
	{27, "config"},
	{28, "contacts"},
	{29, "count"},
	{30, "create"},
	{31, "creation"},
	{32, "debug"},
	{33, "default"},
	{34, "delete"},
	{35, "delivery"},
	{36, "delta"},
	{37, "deny"},
	{38, "digest"},
	{39, "dirty"},
	{40, "duplicate"},
	{41, "elapsed"},
	{42, "enable"},
	{43, "encoding"},
	{44, "error"},
	{45, "event"},
	{46, "expiration"},
	{47, "expired"},
	{48, "fail"},
	{49, "failure"},
	{50, "false"},
	{51, "favorites"},
	{52, "feature"},
	{53, "features"},
	{54, "feature-not-implemented"},
	{55, "field"},
	{56, "first"},
	{57, "free"},
	{58, "from"},
	{59, "g.us"},
	{60, "get"},
	{61, "google"},
	{62, "group"},
	{63, "groups"},
	{64, "http://etherx.jabber.org/streams"},
	{65, "http://jabber.org/protocol/chatstates"},
	{66, "ib"},
	{67, "id"},
	{68, "image"},
	{69, "img"},
	{70, "index"},
	{71, "internal-server-error"},
	{72, "ip"},
	{73, "iq"},
	{74, "item-not-found"},
	{75, "item"},
	{76, "jabber:iq:last"},
	{77, "jabber:iq:privacy"},
	{78, "jabber:x:event"},
	{79, "jid"},
	{80, "kind"},
	{81, "last"},
	{82, "leave"},
	{83, "list"},
	{84, "max"},
	{85, "mechanism"},
	{86, "media"},
	{87, "message_acks"},
	{88, "message"},
	{89, "method"},
	{90, "microsoft"},
	{91, "missing"},
	{92, "modify"},
	{93, "mute"},
	{94, "name"},
	{95, "nokia"},
	{96, "none"},
	{97, "not-acceptable"},
	{98, "not-allowed"},
	{99, "not-authorized"},
	{100, "notification"},
	{101, "notify"},
	{102, "off"},
	{103, "offline"},
	{104, "order"},
	{105, "owner"},
	{106, "owning"},
	{107, "p_o"},
	{108, "p_t"},
	{109, "paid"},
	{110, "participant"},
	{111, "participants"},
	{112, "participating"},
	{113, "paused"},
	{114, "picture"},
	{115, "pin"},
	{116, "ping"},
	{117, "platform"},
	{118, "port"},
	{119, "presence"},
	{120, "preview"},
	{121, "probe"},
	{122, "prop"},
	{123, "props"},
	{124, "query"},
	{125, "raw"},
	{126, "read"},
	{127, "reason"},
	{128, "receipt"},
	{129, "received"},
	{130, "relay"},
	{131, "remote-server-timeout"},
	{132, "remove"},
	{133, "request"},
	{134, "required"},
	{135, "resource-constraint"},
	{136, "resource"},
	{137, "response"},
	{138, "result"},
	{139, "retry"},
	{140, "rim"},
	{141, "s_o"},
	{142, "s_t"},
	{143, "s.us"},
	{144, "s.whatsapp.net"},
	{145, "seconds"},
	{146, "server-error"},
	{147, "server"},
	{148, "service-unavailable"},
	{149, "set"},
	{150, "show"},
	{151, "silent"},
	{152, "stat"},
	{153, "status"},
	{154, "stream:error"},
	{155, "stream:features"},
	{156, "subject"},
	{157, "subscribe"},
	{158, "success"},
	{159, "sync"},
	{160, "t"},
	{161, "text"},
	{162, "timeout"},
	{163, "timestamp"},
	{164, "to"},
	{165, "true"},
	{166, "type"},
	{167, "unavailable"},
	{168, "unsubscribe"},
	{169, "uri"},
	{170, "url"},
	{171, "urn:ietf:params:xml:ns:xmpp-sasl"},
	{172, "urn:ietf:params:xml:ns:xmpp-stanzas"},
	{173, "urn:ietf:params:xml:ns:xmpp-streams"},
	{174, "urn:xmpp:ping"},
	{175, "urn:xmpp:receipts"},
	{176, "urn:xmpp:whatsapp:account"},
	{177, "urn:xmpp:whatsapp:dirty"},
	{178, "urn:xmpp:whatsapp:mms"},
	{179, "urn:xmpp:whatsapp:push"},
	{180, "urn:xmpp:whatsapp"},
	{181, "user"},
	{182, "user-not-found"},
	{183, "value"},
	{184, "version"},
	{185, "w:g"},
	{186, "w:p:r"},
	{187, "w:p"},
	{188, "w:profile:picture"},
	{189, "w"},
	{190, "wait"},
	{191, "WAUTH-2"},
	{192, "x"},
	{193, "xmlns:stream"},
	{194, "xmlns"},
	{195, "1"},
	{196, "chatstate"},
	{197, "crypto"},
	{198, "enc"},
	{199, "class"},
	{200, "off_cnt"},
	{201, "w:g2"},
	{202, "promote"},
	{203, "demote"},
	{204, "creator"},
	{205, ""},
	{206, ""},
	{207, ""},
	{208, ""},
	{209, ""},
	{210, ""},
	{211, ""},
	{212, ""},
	{213, ""},
	{214, ""},
	{215, ""},
	{216, ""},
	{217, ""},
	{218, ""},
	{219, ""},
	{220, ""},
	{221, ""},
	{222, ""},
	{223, ""},
	{224, ""},
	{225, ""},
	{226, ""},
	{227, ""},
	{229, ""},
	{230, ""},
	{231, ""},
	{232, ""},
	{233, ""},
	{234, ""},
	{235, ""},
	{236, "Extended-Dict-1"},
	{237, ""},
	{238, ""},
	{239, ""},
	{240, ""},
	{241, ""},
	{242, ""},
	{243, ""},
	{244, ""},
	{245, ""},
	{246, ""},
	{247, ""},
	{248, ""},
	{249, ""},
	{250, ""},
	{251, ""},
	{252, ""},
	{253, ""},
	{254, ""},
	{255, ""},
	{0,NULL}
};


const value_string strings_list_ext[] = {
	{0,"Bell.caf"},
	{1,"Boing.caf"},
	{2,"Glass.caf"},
	{3,"Harp.caf"},
	{4,"TimePassing.caf"},
	{5,"Tri-tone.caf"},
	{6,"Xylophone.caf"},
	{7,"background"},
	{8,"backoff"},
	{9,"chunked"},
	{10,"context"},
	{11,"full"},
	{12,"in"},
	{13,"interactive"},
	{14,"out"},
	{15,"registration"},
	{16,"sid"},
	{17,"urn:xmpp:whatsapp:sync"},
	{18,"flt"},
	{19,"s16"},
	{20,"u8"},
	{21,"adpcm"},
	{22,"amrnb"},
	{23,"amrwb"},
	{24,"mp3"},
	{25,"pcm"},
	{26,"qcelp"},
	{27,"wma"},
	{28,"h263"},
	{29,"h264"},
	{30,"jpeg"},
	{31,"mpeg4"},
	{32,"wmv"},
	{33,"audio/3gpp"},
	{34,"audio/aac"},
	{35,"audio/amr"},
	{36,"audio/mp4"},
	{37,"audio/mpeg"},
	{38,"audio/ogg"},
	{39,"audio/qcelp"},
	{40,"audio/wav"},
	{41,"audio/webm"},
	{42,"audio/x-caf"},
	{43,"audio/x-ms-wma"},
	{44,"image/gif"},
	{45,"image/jpeg"},
	{46,"image/png"},
	{47,"video/3gpp"},
	{48,"video/avi"},
	{49,"video/mp4"},
	{50,"video/mpeg"},
	{51,"video/quicktime"},
	{52,"video/x-flv"},
	{53,"video/x-ms-asf"},
	{54,"302"},
	{55,"400"},
	{56,"401"},
	{57,"402"},
	{58,"403"},
	{59,"404"},
	{60,"405"},
	{61,"406"},
	{62,"407"},
	{63,"409"},
	{64,"500"},
	{65,"501"},
	{66,"503"},
	{67,"504"},
	{68,"abitrate"},
	{69,"acodec"},
	{70,"app_uptime"},
	{71,"asampfmt"},
	{72,"asampfreq"},
	{73,"audio"},
	{74,"bb_db"},
	{75,"clear"},
	{76,"conflict"},
	{77,"conn_no_nna"},
	{78,"cost"},
	{79,"currency"},
	{80,"duration"},
	{81,"extend"},
	{82,"file"},
	{83,"fps"},
	{84,"g_notify"},
	{85,"g_sound"},
	{86,"gcm"},
	{87,"google_play"},
	{88,"hash"},
	{89,"height"},
	{90,"invalid"},
	{91,"jid-malformed"},
	{92,"latitude"},
	{93,"lc"},
	{94,"lg"},
	{95,"live"},
	{96,"location"},
	{97,"log"},
	{98,"longitude"},
	{99,"max_groups"},
	{100,"max_participants"},
	{101,"max_subject"},
	{102,"mimetype"},
	{103,"mode"},
	{104,"napi_version"},
	{105,"normalize"},
	{106,"orighash"},
	{107,"origin"},
	{108,"passive"},
	{109,"password"},
	{110,"played"},
	{111,"policy-violation"},
	{112,"pop_mean_time"},
	{113,"pop_plus_minus"},
	{114,"price"},
	{115,"pricing"},
	{116,"redeem"},
	{117,"Replaced by new connection"},
	{118,"resume"},
	{119,"signature"},
	{120,"size"},
	{121,"sound"},
	{122,"source"},
	{123,"system-shutdown"},
	{124,"username"},
	{125,"vbitrate"},
	{126,"vcard"},
	{127,"vcodec"},
	{128,"video"},
	{129,"width"},
	{130,"xml-not-well-formed"},
	{131,"checkmarks"},
	{132,"image_max_edge"},
	{133,"image_max_kbytes"},
	{134,"image_quality"},
	{135,"ka"},
	{136,"ka_grow"},
	{137,"ka_shrink"},
	{138,"newmedia"},
	{139,"library"},
	{140,"caption"},
	{141,"forward"},
	{142,"c0"},
	{143,"c1"},
	{144,"c2"},
	{145,"c3"},
	{146,"clock_skew"},
	{147,"cts"},
	{148,"k0"},
	{149,"k1"},
	{150,"login_rtt"},
	{151,"m_id"},
	{152,"nna_msg_rtt"},
	{153,"nna_no_off_count"},
	{154,"nna_offline_ratio"},
	{155,"nna_push_rtt"},
	{156,"no_nna_con_count"},
	{157,"off_msg_rtt"},
	{158,"on_msg_rtt"},
	{159,"stat_name"},
	{160,"sts"},
	{161,"suspect_conn"},
	{162,"lists"},
	{163,"self"},
	{164,"qr"},
	{165,"web"},
	{166,"w:b"},
	{167,"recipient"},
	{168,"w:stats"},
	{169,"forbidden"},
	{170,"aurora.m4r"},
	{171,"bamboo.m4r"},
	{172,"chord.m4r"},
	{173,"circles.m4r"},
	{174,"complete.m4r"},
	{175,"hello.m4r"},
	{176,"input.m4r"},
	{177,"keys.m4r"},
	{178,"note.m4r"},
	{179,"popcorn.m4r"},
	{180,"pulse.m4r"},
	{181,"synth.m4r"},
	{182,"filehash"},
	{183,""},
	{184,""},
	{185,""},
	{186,""},
	{187,""},
	{188,""},
	{189,""},
	{190,""},
	{191,""},
	{192,""},
	{193,""},
	{194,""},
	{195,""},
	{196,""},
	{197,""},
	{198,""},
	{199,""},
	{200,""},
	{201,""},
	{202,""},
	{203,""},
	{204,""},
	{205,""},
	{206,""},
	{207,""},
	{208,""},
	{209,""},
	{210,""},
	{211,""},
	{212,""},
	{213,""},
	{214,""},
	{215,""},
	{216,""},
	{217,""},
	{218,""},
	{219,""},
	{220,""},
	{221,""},
	{222,""},
	{223,""},
	{224,""},
	{225,""},
	{226,""},
	{227,""},
	{228,""},
	{229,""},
	{230,""},
	{231,""},
	{232,""},
	{233,""},
	{234,""},
	{235,""},
	{236,""},
	{237,""},
	{238,""},
	{239,""},
	{240,""},
	{241,""},
	{242,""},
	{243,""},
	{244,""},
	{245,""},
	{246,""},
	{247,""},
	{248,""},
	{249,""},
	{250,""},
	{251,""},
	{252,""},
	{253,""},
	{254,""},
	{255,""},
	{0,NULL}
};

